### ISSUE TITLE
Bad Request at create_envelope

### ISSUE THREAD

**Issue by MatthewSchultz** [docusign/eg-01-ruby-jwt#1]
So I'm trying to run the reference implementation (this), and I'm able to login and get a JWT token, but it looks like, when trying to create an envelope, I get a bad request error returned.

Output from main.rb:
```
PS C:\Users\matt\Projects\RubyDocuSignExample> ruby main.rb

Sending an envelope...
Starting up: fetching token
Received token
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/docusign_esign-1.0.0/lib/docusign_esign/api_client.rb:66:in `call_api': Bad Request (DocuSign_eSign::ApiError)
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/docusign_esign-1.0.0/lib/docusign_esign/api/envelopes_api.rb:889:in `create_envelope_with_http_info'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/docusign_esign-1.0.0/lib/docusign_esign/api/envelopes_api.rb:853:in `create_envelope'
        from C:/Users/matt/Projects/RubyDocuSignExample/send_envelope.rb:42:in `sendEnvelope'
        from main.rb:14:in `run'
        from main.rb:34:in `<main>'
```
Any ideas as to what's going wrong?

**Comment by LarryKlugerDS** [comment]
Hi,

Have you granted permission for your client id (Integration key) to impersonate you?

If not, then you need to do so either for just the user you're starting with or for all users in your organization via Organization Admin.

Steps for granting permission for just the individual:
Individual user consent to allow impersonation by a JWT token request is done by following the first step in the OAuth Authorization Code Grant flow.

Do this by 

1. Open demo.docusign.net, login, and go to the Admin Tool.
2. Add `https://docusign.com` as a redirect URI to your Integration Key (client id)
3. opening a browser and visiting the following URL:

````
https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=CLIENT_ID&redirect_uri=https://docusign.com
````
Where CLIENT_ID is your client id.

You should see first a login screen (unless you're still logged in), then a permissions grant screen.
After granting permission, you can go back and delete the Redirect URI from your client id if you wish.

Next, retry your Ruby app.

More information on this step: https://www.docusign.com/blog/dsdev-using-the-oauth-jwt-flow/

**Comment by MatthewSchultz** [comment]
Yes I have.

As of yesterday afternoon, I wasn't even able to get a token - though thanks to comments on the SDK's github page and the video documentation for the JWT flow, I discovered that I needed to complete this step to enable this on my account.

I did that yesterday, and can now authenticate and get a JWT token. For good measure, I completed the step again moments ago, and wasn't even asked to authorize it - it just went straight to the redirect (makes sense - it should be already authorized).

**Comment by LarryKlugerDS** [comment]
Hmmm. Ok, so that means there's an issue with the Envelopes::create request. Some questions and next step:

1. Check that the config file is filled out. Note that the email addresses for signer and cc can be the same, but in that case the names need to be different.
2. The next debugging step is to look at the API call. Please use the 
[API logger](https://support.docusign.com/guides/ndse-user-guide-api-request-logging)
and then post the request / response of the Envelopes::create call.

Thanks,
Larry

**Comment by MatthewSchultz** [comment]
```
  #### Copy this file to ds_config.rb and update it.
  #### ds_config.rb is in .gitignore so it will NOT be stored in git

  # Use account.docusign.com for production
  @aud ="account-d.docusign.com"
  # client_id is the same as Integrator Key
  @client_id = "integrator_key_is_here"
  # The user's email can't be used here:
  @impersonated_user_guid = "user_guid_from_user_page_is_here"
  # If a target account is not specified then the user's default
  # account will be used
  @target_account_id = "FALSE"
  @signer_email ='valid@email.com'
  @signer_name ='Matthew Schultz'
  @cc_email = 'other.valid@email.com'
  @cc_name = 'Tester Test'
```

A (redacted) copy of my ds_config.rb file.

**Comment by MatthewSchultz** [comment]
```
POST https://demo.docusign.net:7802/restapi/v2/accounts/3eeef54b-8ae0-45b0-99d6-28f258d3ae18/envelopes

TraceToken: 338ac941-6ce3-4dd5-9317-fe9590ea2bb5
Timestamp: 2018-08-07T17:22:54.4540648Z

Content-Length: 4495
Content-Type: application/json
Accept: application/json
Authorization: Bearer [omitted]
Host: demo.docusign.net
User-Agent: Swagger-Codegen/1.0.0/ruby
X-DocuSign-SDK: Ruby
X-SecurityProtocol-Version: TLSv1.2
X-SecurityProtocol-CipherSuite: ECDHE-RSA-AES256-GCM-SHA384
x-forwarded-for: 199.167.83.154

{"documents":[{"documentBase64":"CiAgICA8IURPQ1RZUEUgaHRtbD4KICAgIDxodG1sPgogICAgICA8aGVhZD4K\nICAgICAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+CiAgICAgIDwvaGVhZD4K\nICAgICAgPGJvZHkgc3R5bGU9ImZvbnQtZmFtaWx5OnNhbnMtc2VyaWY7bWFy\nZ2luLWxlZnQ6MmVtOyI+CiAgICAgICAgPGgxIHN0eWxlPSJmb250LWZhbWls\neTogJ1RyZWJ1Y2hldCBNUycsIEhlbHZldGljYSwgc2Fucy1zZXJpZjsiCiAg\nICAgICAgICAgICAgY29sb3I6IGRhcmtibHVlO21hcmdpbi1ib3R0b206IDA7\nIj5Xb3JsZCBXaWRlIENvcnA8L2gxPgogICAgICAgIDxoMiBzdHlsZT0iZm9u\ndC1mYW1pbHk6ICdUcmVidWNoZXQgTVMnLCBIZWx2ZXRpY2EsIHNhbnMtc2Vy\naWY7CiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMHB4O21hcmdpbi1ib3R0\nb206IDMuNWVtO2ZvbnQtc2l6ZTogMWVtOwogICAgICAgICAgICAgIGNvbG9y\nOiBkYXJrYmx1ZTsiPk9yZGVyIFByb2Nlc3NpbmcgRGl2aXNpb248L2gyPgog\nICAgICAgIDxoND5PcmRlcmVkIGJ5IE1hdHRoZXcgU2NodWx0ejwvaDQ+CiAg\nICAgICAgPHAgc3R5bGU9Im1hcmdpbi10b3A6MGVtOyBtYXJnaW4tYm90dG9t\nOjBlbTsiPkVtYWlsOiAgbXNjaHVsdHpAbGVhcm5pbmdtZWFuc2Z1bi5jb20g\nPC9wPgogICAgICAgIDxwIHN0eWxlPSJtYXJnaW4tdG9wOjBlbTsgbWFyZ2lu\nLWJvdHRvbTowZW07Ij5Db3B5IHRvOiBUZXN0ZXIgVGVzdCAsIG1hdHRAbGVh\ncm5pbmdtZWFuc2Z1bi5jb20gPC9wPgogICAgICAgIDxwIHN0eWxlPSJtYXJn\naW4tdG9wOjNlbTsiPgogICAgICAgICAgQ2FuZHkgYm9uYm9uIHBhc3RyeSBq\ndWp1YmVzIGxvbGxpcG9wIHdhZmVyIGJpc2N1aXQgYmlzY3VpdC4gVG9wcGlu\nZyBicm93bmllIHNlc2FtZSBzbmFwcwogICAgICAgICAgc3dlZXQgcm9sbCBw\naWUuIENyb2lzc2FudCBkYW5pc2ggYmlzY3VpdCBzb3VmZmzDqSBjYXJhbWVs\ncyBqdWp1YmVzIGplbGx5LiBEcmFnw6llIGRhbmlzaCBjYXJhbWVscyBsZW1v\nbgogICAgICAgICAgZHJvcHMgZHJhZ8OpZS4gR3VtbWkgYmVhcnMgY3VwY2Fr\nZSBiaXNjdWl0IHRpcmFtaXN1IHN1Z2FyIHBsdW0gcGFzdHJ5LgogICAgICAg\nICAgRHJhZ8OpZSBndW1taWVzIGFwcGxpY2FrZSBwdWRkaW5nIGxpcXVvcmlj\nZS4gRG9udXQganVqdWJlcyBvYXQgY2FrZSBqZWxseS1vLiBEZXNzZXJ0IGJl\nYXIgY2xhdyBjaG9jb2xhdGUKICAgICAgICAgIGNha2UgZ3VtbWllcyBsb2xs\naXBvcCBzdWdhciBwbHVtIGljZSBjcmVhbSBndW1taWVzIGNoZWVzZWNha2Uu\nCiAgICAgICAgPC9wPgogICAgICAgIDwhLS0gTm90ZSB0aGUgYW5jaG9yIHRh\nZyBmb3IgdGhlIHNpZ25hdHVyZSBmaWVsZCBpcyBpbiB3aGl0ZS4gLS0+CiAg\nICAgICAgPGgzIHN0eWxlPSJtYXJnaW4tdG9wOjNlbTsiPkFncmVlZDogPHNw\nYW4gc3R5bGU9ImNvbG9yOndoaXRlOyI+KipzaWduYXR1cmVfMSoqPC9zcGFu\nPjwvaDM+CiAgICAgIDwvYm9keT4KICAgIDwvaHRtbD4KICA=\n","documentId":"1","fileExtension":"html","name":"Order acknowledgement"},{"documentBase64":"UEsDBBQABgAIAAAAIQAMrgRrmAEAAJAHAAATAAgCW0NvbnRlbnRfVHlwZXNd\nLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMVUtLw0AQvgv+h7BXabYq\niEjTHnwctWAFr+tmkm7dF7vT1793kmgQia3aKl4Cycz3mN2ZyWC0MjpZQIjK\n2Ywdp32WgJUuV7bM2MPkpnfOkojC5kI7CxlbQ2Sj4eHBYLL2EBNC25ixKaK/\n4DzKKRgRU+fBUqRwwQik11ByL+SzKIGf9PtnXDqLYLGHFQcbDq6gEHONyfWK\nPjdOCM6SyyavksqY8F4rKZDCvIryTlwAHTcAFzb/4K736iwlZJ0Tp8rHo88V\nZr78IKBMVdnMQ/kJBFVRdGLqAGHu6AaCyiEZi4C3wlACX7qQ89zJuSFQuvk8\nOspyRaEktPiKzQcnIUa6WqPTNmKEsm/ldvmQ84jOPA==\n","documentId":"2","fileExtension":"docx","name":"Battle Plan"},{"documentBase64":"JVBERi0xLjMKJcTl8uXrp/Og0MTGCjQgMCBvYmoKPDwgL0xlbmd0aCA1IDAg\nUiAvRmlsdGVyIC9GbGF0ZURlY29kZSA+PgpzdHJlYW0KeAGlm1mT5EYRx9/1\nKYrDoAGP3Lq61Y/Y64cFgrWJIUwE5sG0x9jMzu5avbtm+fRkHfnLUuuYJnBs\nuDWqrDz+eVRWSfrRfel+dHXj//XD4A77wY337iv3yn3y2bl2p7PbuV1VN313\n3DVy1R723WG3d+eTzNtVTefH40W9b6tDv6vd/niouq44PbpP71y9CwT83j26\nT+7uale7u+9c6W7c3b/c53dBjQt2h111HHb9lN2u2u1ExN0Jhipgwvhvrvzq\n9Y0IKceX37qvfvj23n0mf//d3f1epBXe6Km0tjlWfds3SZqLyt8Gce2GuCLa\nMb5ZN0S4Vk3bdVPWXR+QSz9R+TZx+9k6MwP5sK+GpKbXsvFK9kNg\n","documentId":"3","fileExtension":"pdf","name":"Lorem Ipsum"}],"emailSubject":"Please sign this document sent from Ruby SDK","recipients":{"carbonCopies":[{"email":"matt@learningmeansfun.com","name":"Tester Test","recipientId":"2","routingOrder":"2"}],"signers":[{"email":"mschultz@learningmeansfun.com","name":"Matthew Schultz","recipientId":"1","routingOrder":"1","tabs":{"signHereTabs":[{"anchorString":"**signature_1**","anchorUnits":"pixels","anchorXOffset":"20","anchorYOffset":"10"},{"anchorString":"/sn1/","anchorUnits":"pixels","anchorXOffset":"20","anchorYOffset":"10"}]}}]},"status":"sent"}
400 BadRequest
Content-Type: application/json; charset=utf-8
X-DocuSign-TraceToken: 338ac941-6ce3-4dd5-9317-fe9590ea2bb5

{
  "errorCode": "UNABLE_TO_CONVERT_DOCUMENT",
  "message": "System was unable to convert this document to a PDF. Unable to convert Document(Battle Plan.docx) to a PDF. Error: UserId:8c0cf68e-ffd4-4fe6-876e-c39edf57f7ba IPAddress:199.167.83.154 Source:ApiRESTv2:Failed to convert Battle Plan.docx"
}
```

**Comment by MatthewSchultz** [comment]
I removed doc2 (the word file), only to be rewarded with:

```
POST https://demo.docusign.net:7802/restapi/v2/accounts/3eeef54b-8ae0-45b0-99d6-28f258d3ae18/envelopes

TraceToken: 07be0c03-a215-4714-8c40-f1a1faa2d184
Timestamp: 2018-08-07T17:33:19.0939085Z

Content-Length: 3250
Content-Type: application/json
Accept: application/json
Authorization: Bearer [omitted]
Host: demo.docusign.net
User-Agent: Swagger-Codegen/1.0.0/ruby
X-DocuSign-SDK: Ruby
X-SecurityProtocol-Version: TLSv1.2
X-SecurityProtocol-CipherSuite: ECDHE-RSA-AES256-GCM-SHA384
x-forwarded-for: 199.167.83.154

{"documents":[{"documentBase64":"CiAgICA8IURPQ1RZUEUgaHRtbD4KICAgIDxodG1sPgogICAgICA8aGVhZD4K\nICAgICAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+CiAgICAgIDwvaGVhZD4K\nICAgICAgPGJvZHkgc3R5bGU9ImZvbnQtZmFtaWx5OnNhbnMtc2VyaWY7bWFy\nZ2luLWxlZnQ6MmVtOyI+CiAgICAgICAgPGgxIHN0eWxlPSJmb250LWZhbWls\neTogJ1RyZWJ1Y2hldCBNUycsIEhlbHZldGljYSwgc2Fucy1zZXJpZjsiCiAg\nICAgICAgICAgICAgY29sb3I6IGRhcmtibHVlO21hcmdpbi1ib3R0b206IDA7\nIj5Xb3JsZCBXaWRlIENvcnA8L2gxPgogICAgICAgIDxoMiBzdHlsZT0iZm9u\ndC1mYW1pbHk6ICdUcmVidWNoZXQgTVMnLCBIZWx2ZXRpY2EsIHNhbnMtc2Vy\naWY7CiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMHB4O21hcmdpbi1ib3R0\nb206IDMuNWVtO2ZvbnQtc2l6ZTogMWVtOwogICAgICAgICAgICAgIGNvbG9y\nOiBkYXJrYmx1ZTsiPk9yZGVyIFByb2Nlc3NpbmcgRGl2aXNpb248L2gyPgog\nICAgICAgIDxoND5PcmRlcmVkIGJ5IE1hdHRoZXcgU2NodWx0ejwvaDQ+CiAg\nICAgICAgPHAgc3R5bGU9Im1hcmdpbi10b3A6MGVtOyBtYXJnaW4tYm90dG9t\nOjBlbTsiPkVtYWlsOiAgbXNjaHVsdHpAbGVhcm5pbmdtZWFuc2Z1bi5jb20g\nPC9wPgogICAgICAgIDxwIHN0eWxlPSJtYXJnaW4tdG9wOjBlbTsgbWFyZ2lu\nLWJvdHRvbTowZW07Ij5Db3B5IHRvOiBUZXN0ZXIgVGVzdCAsIG1hdHRAbGVh\ncm5pbmdtZWFuc2Z1bi5jb20gPC9wPgogICAgICAgIDxwIHN0eWxlPSJtYXJn\naW4tdG9wOjNlbTsiPgogICAgICAgICAgQ2FuZHkgYm9uYm9uIHBhc3RyeSBq\ndWp1YmVzIGxvbGxpcG9wIHdhZmVyIGJpc2N1aXQgYmlzY3VpdC4gVG9wcGlu\nZyBicm93bmllIHNlc2FtZSBzbmFwcwogICAgICAgICAgc3dlZXQgcm9sbCBw\naWUuIENyb2lzc2FudCBkYW5pc2ggYmlzY3VpdCBzb3VmZmzDqSBjYXJhbWVs\ncyBqdWp1YmVzIGplbGx5LiBEcmFnw6llIGRhbmlzaCBjYXJhbWVscyBsZW1v\nbgogICAgICAgICAgZHJvcHMgZHJhZ8OpZS4gR3VtbWkgYmVhcnMgY3VwY2Fr\nZSBiaXNjdWl0IHRpcmFtaXN1IHN1Z2FyIHBsdW0gcGFzdHJ5LgogICAgICAg\nICAgRHJhZ8OpZSBndW1taWVzIGFwcGxpY2FrZSBwdWRkaW5nIGxpcXVvcmlj\nZS4gRG9udXQganVqdWJlcyBvYXQgY2FrZSBqZWxseS1vLiBEZXNzZXJ0IGJl\nYXIgY2xhdyBjaG9jb2xhdGUKICAgICAgICAgIGNha2UgZ3VtbWllcyBsb2xs\naXBvcCBzdWdhciBwbHVtIGljZSBjcmVhbSBndW1taWVzIGNoZWVzZWNha2Uu\nCiAgICAgICAgPC9wPgogICAgICAgIDwhLS0gTm90ZSB0aGUgYW5jaG9yIHRh\nZyBmb3IgdGhlIHNpZ25hdHVyZSBmaWVsZCBpcyBpbiB3aGl0ZS4gLS0+CiAg\nICAgICAgPGgzIHN0eWxlPSJtYXJnaW4tdG9wOjNlbTsiPkFncmVlZDogPHNw\nYW4gc3R5bGU9ImNvbG9yOndoaXRlOyI+KipzaWduYXR1cmVfMSoqPC9zcGFu\nPjwvaDM+CiAgICAgIDwvYm9keT4KICAgIDwvaHRtbD4KICA=\n","documentId":"1","fileExtension":"html","name":"Order acknowledgement"},{"documentBase64":"JVBERi0xLjMKJcTl8uXrp/Og0MTGCjQgMCBvYmoKPDwgL0xlbmd0aCA1IDAg\nUiAvRmlsdGVyIC9GbGF0ZURlY29kZSA+PgpzdHJlYW0KeAGlm1mT5EYRx9/1\nKYrDoAGP3Lq61Y/Y64cFgrWJIUwE5sG0x9jMzu5avbtm+fRkHfnLUuuYJnBs\nuDWqrDz+eVRWSfrRfel+dHXj//XD4A77wY337iv3yn3y2bl2p7PbuV1VN313\n3DVy1R723WG3d+eTzNtVTefH40W9b6tDv6vd/niouq44PbpP71y9CwT83j26\nT+7uale7u+9c6W7c3b/c53dBjQt2h111HHb9lN2u2u1ExN0Jhipgwvhvrvzq\n9Y0IKceX37qvfvj23n0mf//d3f1epBXe6Km0tjlWfds3SZqLyt8Gce2GuCLa\nMb5ZN0S4Vk3bdVPWXR+QSz9R+TZx+9k6MwP5sK+GpKbXsvFK9kNg\n","documentId":"3","fileExtension":"pdf","name":"Lorem Ipsum"}],"emailSubject":"Please sign this document sent from Ruby SDK","recipients":{"carbonCopies":[{"email":"matt@learningmeansfun.com","name":"Tester Test","recipientId":"2","routingOrder":"2"}],"signers":[{"email":"mschultz@learningmeansfun.com","name":"Matthew Schultz","recipientId":"1","routingOrder":"1","tabs":{"signHereTabs":[{"anchorString":"**signature_1**","anchorUnits":"pixels","anchorXOffset":"20","anchorYOffset":"10"},{"anchorString":"/sn1/","anchorUnits":"pixels","anchorXOffset":"20","anchorYOffset":"10"}]}}]},"status":"sent"}
400 BadRequest
Content-Type: application/json; charset=utf-8
X-DocuSign-TraceToken: 07be0c03-a215-4714-8c40-f1a1faa2d184

{
  "errorCode": "PDF_VALIDATION_FAILED",
  "message": "The validation of the PDF file failed."
}
```

Wondering if it's not uploading documents correctly?

**Comment by LarryKlugerDS** [comment]
Never mind the \n issue, that's fine. Are you using windows? (We're developing on Macs.)

I think the issue is reading the files in binary mode. I will be pushing an update shortly.

**Comment by LarryKlugerDS** [comment]
I've pushed a new version of the example that should both fix the Windows issue you ran into and also now provides much better error information when there's a problem.

Please re-download and try it. Remember to first save your ds_config and private key file somewhere so they are not lost. 

Please let me know if this solves the problem for you.

Many thanks,
Larry

**Comment by LarryKlugerDS** [comment]
SInce I haven't heard further, I will assume that my fix was successful. Please re-open this issue if the problem is not cured.
